# Generated by Django 4.0.4 on 2022-05-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('RecordId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('DateOfBirth', models.DateField()),
                ('Address', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=20)),
                ('Zipcode', models.CharField(max_length=20)),
                ('LandLine', models.CharField(max_length=20)),
                ('CellPhone', models.CharField(max_length=20)),
                ('Infected', models.BooleanField(max_length=20)),
                ('previousDiseases', models.CharField(max_length=50)),
            ],
        ),
    ]
